# Generated by Django 3.2.16 on 2022-10-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='number_of_sort',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='number_of_sort',
            field=models.IntegerField(),
        ),
    ]
